#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

wmake $targetType timeIntegrators
wmake $targetType finiteVolume
wmake $targetType fluxSchemes

# -----------------------------------------------------------------------------

