#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------
# set -x

wclean $targetType fluxSchemes
wclean $targetType finiteVolume
wclean $targetType timeIntegrators

#------------------------------------------------------------------------------
